version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /storage/data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '-alertmanager.url=http://alertmanager:9093'
      - '--web.external-url=https://prometheus.intellizy.net'
    deploy:
      labels:
        - "traefik.docker.network=proxy"
        #- "traefik.domain=prometheus.intellizy.net"
        - "traefik.enable=true"
        - "traefik.port=9090"
        - "traefik.backend=monitor_prometheus"
        - "traefik.frontend.rule=Host:prometheus.intellizy.net"
        #- "traefik.frontend.auth.basic=admin:Mafalda01"
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - source: alert.rules
        target: /etc/prometheus/alert.rules
    networks:
      - prometheus
      - proxy

alertmanager: 
    image: prom/alertmanager
    volumes:
      - /storage/data/prometheus/alertmanager:/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
      - '-web.external-url=https://alertmanager.intellizy.net'
    deploy:
      labels:
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
        - "traefik.port=9093"
        - "traefik.backend=monitor_alertmanager"
        - "traefik.frontend.rule=Host:alertmanager.intellizy.net"
        #- "traefik.frontend.auth.basic=admin:$$apr1$$..."
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/config.yml
    networks:
      - prometheus
      - proxy

  grafana:
    image: grafana/grafana
    volumes:
      - /storage/data/prometheus/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Mafalda01!
      # Be carefull with GF_SECURITY_ADMIN_USER (only enabled at database creation)
      - GF_SECURITY_ADMIN_USER=admin
      # To disable basic auth for Grafana
      #- GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_DOMAIN=perf.intellizy.net
      - GF_SERVER_ROOT_URL=https://perf.intellizy.net
    deploy:
      labels:
        - "traefik.docker.network=proxy"
        #- "traefik.domain=perf.intellizy.net"
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=monitor_grafana"
        - "traefik.frontend.rule=Host:perf.intellizy.net"
        #- "traefik.frontend.auth.basic=admin:Mafalda01"
    networks:
      - prometheus 
      - proxy

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 80M
    networks:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '--path.procfs=/host/proc --path.sysfs=/host/sys --collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" --collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
    hostname: "{{.Node.ID}}"
    environment:
      HOST_HOSTNAME: /etc/hostname
    networks:
      - prometheus

  # blackbox-exporter:
  #   image: prom/blackbox-exporter
  #   command: '--config.file=/config/blackbox.yml'
  #   # with debug
  #   #command: '--config.file=/config/blackbox.yml --log.level=debug'
  #   networks:
  #     - prometheus
  #     - proxy
  #   configs:
  #     - source: blackbox.yml
  #       target: /config/blackbox.yml

configs:
  prometheus.yml:
    file: ./configs/prometheus.yml
  alert.rules:
    file: ./configs/alert.rules
  alertmanager.yml:
    file: ./configs/alertmanager.yml

networks:
  prometheus:
    driver: overlay
  proxy:
    external: true
