version: '3.2'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /storage/data/prometheus/configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - /storage/data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://prometheus.intellizy.net'
    deploy:
      labels:
        - "traefik.docker.network=proxy"
        - "traefik.domain=prometheus.intellizy.net"
        - "traefik.enable=true"
        - "traefik.port=9090"
        - "traefik.backend=monitor_prometheus"
        - "traefik.frontend.rule=Host:prometheus.intellizy.net"
    #depends_on:
    #  - cadvisor
    #  - node-exporter
    #  - blackbox-exporter
    networks:
      - prometheus
      - proxy

  grafana:
    image: grafana/grafana
    volumes:
      - /storage/data/prometheus/grafana:/var/lib/grafana
    #depends_on:
    # - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Mafalda01!
      # Be carefull with GF_SECURITY_ADMIN_USER (only enabled at database creation)
      - GF_SECURITY_ADMIN_USER=admin
      # To disable basic auth for Grafana
      #- GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_DOMAIN=perf.intellizy.net
      - GF_SERVER_ROOT_URL=https://perf.intellizy.net
    deploy:
      labels:
        - "traefik.docker.network=proxy"
        - "traefik.domain=perf.intellizy.net"
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=monitor_grafana"
        - "traefik.frontend.rule=Host:perf.intellizy.net"
    networks:
      - prometheus 
      - proxy

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    #command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 80M
    networks:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '--path.procfs=/host/proc --path.sysfs=/host/sys --collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" --collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
    hostname: "{{.Node.ID}}"
    environment:
      #HOST_HOSTNAME: /etc/host_hostname
      HOST_HOSTNAME: /etc/hostname
    networks:
      - prometheus

  # blackbox-exporter:
  #   image: prom/blackbox-exporter
  #   command: '--config.file=/config/blackbox.yml'
  #   # with debug
  #   #command: '--config.file=/config/blackbox.yml --log.level=debug'
  #   networks:
  #     - prometheus
  #     - proxy
  #   configs:
  #     - source: blackbox.yml
  #       target: /config/blackbox.yml

networks:
  prometheus:
    driver: overlay
  proxy:
    external: true
