groups:
- name: alert.rules
  rules:
  - alert: high_cpu_usage_on_node
    expr: sum by(instance) (rate(process_cpu_seconds_total[5m])) * 100 > 70
    for: 5m
    annotations:
      description: '{{ $labels.instance }} is using a LOT of CPU. CPU usage is {{
        humanize $value}}%.'
      summary: HIGH CPU USAGE WARNING ON '{{ $labels.instance }}'
  - alert: high_memory_usage_on_node
    expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)
      * 100 > 85
    for: 5m
    annotations:
      description: '{{ $labels.instance }} is using a LOT of MEMORY. MEMORY usage
        is over {{ humanize $value}}%.'
      summary: HIGH MEMORY USAGE WARNING TASK ON '{{ $labels.host }}'
  - alert: high_la_usage_on_node
    expr: node_load5 > 5
    for: 5m
    annotations:
      description: '{{ $labels.instance }} has a high load average. Load Average 5m
        is {{ humanize $value}}.'
      summary: HIGH LOAD AVERAGE WARNING ON '{{ $labels.instance }}'
  - alert: monitoring_service_down
    expr: up == 0
    for: 5m
    annotations:
      description: The monitoring service '{{ $labels.job }}' is down.
      summary: 'MONITORING SERVICE DOWN WARNING: NODE ''{{ $labels.host }}'''
  - alert: node_running_out_of_disk_space
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"})
      * 100 / node_filesystem_size_bytes{mountpoint="/"} > 80
    for: 5m
    annotations:
      description: More than 80% of disk used. Disk usage {{ humanize $value }}%.
      summary: 'LOW DISK SPACE WARING: NODE ''{{ $labels.host }}'''
  - alert: disk_will_fill_in_8_hours
    expr: predict_linear(node_filesystem_free_bytes{mountpoint="/"}[1h], 8 * 3600)
      < 0
    for: 5m
    annotations:
      description: '{{ $labels.instance }} is writing a lot.'
      summary: 'DISK SPACE FULL IN 8 HOURS: NODE ''{{ $labels.host }}'''
  - alert: high_cpu_usage_on_container
    expr: sum by(container_label_com_docker_swarm_task_name, instance) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~".+"}[5m]))
      * 100 > 200
    for: 5m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} is using
        a LOT of CPU. CPU usage is {{ humanize $value}}%.'
      summary: 'HIGH CPU USAGE WARNING: TASK ''{{ $labels.container_label_com_docker_swarm_task_name
        }}'' on ''{{ $labels.instance }}'''
  - alert: container_eating_memory
    expr: sum by(instance, name) (container_memory_rss{container_label_com_docker_swarm_task_name=~".+"})
      > 2.5e+09
    for: 5m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} is eating
        up a LOT of memory. Memory consumption of {{ $labels.container_label_com_docker_swarm_task_name
        }} is at {{ humanize $value}}.'
      summary: 'HIGH MEMORY USAGE WARNING: TASK ''{{ $labels.container_label_com_docker_swarm_task_name
        }}'' on ''{{ $labels.instance }}'''
  - alert: site_down
    expr: probe_success == 0
    for: 5m
    annotations:
      description: '{{$labels.instance}} has been down for more than 10 minutes.'
      summary: '{{$labels.instance}} down'
  - alert: container_not_in_running_state
    expr: sum by(container_label_com_docker_stack_namespace) (container_tasks_state{state!="running"})
      > 0
    for: 1m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} has a
        container not in running state on {{ $labels.instance }}'
      summary: Container not in running state in stack '{{ $labels.container_label_com_docker_swarm_task_name
        }}' on '{{ $labels.instance }}'
